### ISSUE TITLE
dspec failing to install correctly in fresh environment

### ISSUE THREAD

**Issue by talonmyburgh** [landmanbester/Jovywood#5]
In a fresh `Python 3.9.18` environment, after only installing Jovywood, `dspec` installs but errors when running it in any way.
Trying `dspec -h` yeilds:
```
Traceback (most recent call last):
  File "/home/myburgh/venv/jovy_venv/bin/dspec", line 33, in <module>
    sys.exit(load_entry_point('Jovywood==0.0.1', 'console_scripts', 'dspec')())
  File "/home/myburgh/venv/jovy_venv/bin/dspec", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/jove/dspec.py", line 10, in <module>
    from jove.workers import gpr_smooth
ModuleNotFoundError: No module named 'jove.workers'
```
This is possibly due to the `Jovywood/jove/workers` not containing a blank `__init__.py` file.

**Comment by talonmyburgh** [comment]
After adding a blank `__init__.py` it appears to have patched the above bug but introduces a new one. `dspec -h` now yeilds:
```
Traceback (most recent call last):
  File "/home/myburgh/venv/jovy_venv/bin/dspec", line 33, in <module>
    sys.exit(load_entry_point('Jovywood==0.0.1', 'console_scripts', 'dspec')())
  File "/home/myburgh/venv/jovy_venv/bin/dspec", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/jove/dspec.py", line 10, in <module>
    from jove.workers import gpr_smooth
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/jove/workers/gpr_smooth.py", line 13, in <module>
    for key in schema.gpr_smooth["inputs"].keys():
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/myburgh/venv/jovy_venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key gpr_smooth
    full_key: gpr_smooth
    object_type=dict
```

**Comment by landmanbester** [comment]
Yeah, sorry the code is a bit dated. I updated the `stimela` requirement in the p3.10 branch. Installing it in a fresh python3.10 venv seems to work. I can also do (note the `-` instead of `_`)
```
$ dspec gpr-smooth --help
```
and running 
```
$ stimela doc jove/stimela_cabs.yaml
2024-05-27 12:15:10 STIMELA INFO: starting
2024-05-27 12:15:10 STIMELA INFO: loading configuration
2024-05-27 12:15:10 STIMELA INFO: loading config from /home/landman/venvs/jove/lib/python3.10/site-packages/stimela/stimela.conf
2024-05-27 12:15:10 STIMELA INFO: loaded config from /home/landman/venvs/jove/lib/python3.10/site-packages/stimela/stimela.conf
2024-05-27 12:15:10 STIMELA INFO: saving config dependencies to ./stimela.config.deps
2024-05-27 12:15:10 STIMELA INFO: will load recipe/config file jove/stimela_cabs.yaml
2024-05-27 12:15:10 STIMELA INFO: loaded 1 cab definition(s) and 0 recipe(s)
stimela doc jove/stimela_cabs.yaml
└── Cab: gpr.smooth
    ├── command: jove.workers.gpr_smooth.gpr_smooth
    ├── Required inputs:
    │   └── basename  str  Path to .norm.fits file.
    └── Optional inputs:
        └── mad_threshold  float  MAD flagging threshold [default: 3.0]
            lnu            float  Degree of smoothing in freq direction. Must be in [0, 1) with 0 -> no smoothing. [default: 0.01]
            lt             float  Degree of smoothing in time direction. Must be in [0, 1) with 0 -> no smoothing. [default: 0.001]
            nthreads       int    Number of threads per Stokes product. [default: 8]
            t0             int    Start time [default: 0]
            tf             int    End time [default: -1]
            nu0            int    Start freq [default: 0]
            nuf            int    End freq [default: -1]
            sigma_min      float  Lower cut off for smoothed variance [default: 1e-06]
            do_gpr         bool   Whether to perform GPR or not [default: True]
```
also seems to work. Can you see if that works for you a fresh venv?

**Comment by talonmyburgh** [comment]
I'm sorry, just tried again - deleted `venv` and recreated a 3.10 instance. Also recloned repo and checked out `p3.10`.
I get:
```
(jovy_venv) myburgh@bbking:~/repos/Jovywood$ dspec gpr-smooth --help
Traceback (most recent call last):
  File "/home/myburgh/venv/jovy_venv/bin/dspec", line 33, in <module>
    sys.exit(load_entry_point('Jovywood==0.0.1', 'console_scripts', 'dspec')())
  File "/home/myburgh/venv/jovy_venv/bin/dspec", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/jove/dspec.py", line 9, in <module>
    from jove.workers import gpr_smooth
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/jove/workers/gpr_smooth.py", line 13, in <module>
    for key in schema.gpr_smooth["inputs"].keys():
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key gpr_smooth
    full_key: gpr_smooth
    object_type=dict
```
and
```
(jovy_venv) myburgh@bbking:~/repos/Jovywood$ stimela doc jove/stimela_cabs.yaml
2024-05-30 19:19:47 STIMELA INFO: starting                                                                                                                                                                
2024-05-30 19:19:47 STIMELA INFO: loading configuration                                                                                                                                                   
2024-05-30 19:19:47 STIMELA INFO: loading config from /home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/stimela/stimela.conf                                                                      
2024-05-30 19:19:47 STIMELA INFO: loaded config from /home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/stimela/stimela.conf                                                                       
2024-05-30 19:19:47 STIMELA INFO: saving config dependencies to ./stimela.config.deps                                                                                                                     
2024-05-30 19:19:47 STIMELA INFO: will load recipe/config file jove/stimela_cabs.yaml                                                                                                                     
2024-05-30 19:19:47 STIMELA ERROR: error loading jove/stimela_cabs.yaml: config error at cabs.gpr.smooth in stimela_cabs.yaml: _include (jove.parser)gpr_smooth.yaml:                                     
/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/jove/parser/gpr_smooth.yaml does not exist
```
Not sure what is happening :/

**Comment by talonmyburgh** [comment]
@landmanbester just tried again in-case something was amiss. Still does not work.

**Comment by landmanbester** [comment]
Weird. Might be quickest if you point me at the data (even better if it's on bbking). Can do a meeting before 12h tomorrow if you want

**Comment by talonmyburgh** [comment]
Dynamic spectra products are at:
`/home/myburgh/PARROT_dynspec/1624216341_1rad_30noff_dynspec_weight_DynSpecs_corr-1624216341`

I have a clone of your Jovywood at:
`/home/myburgh/repos/Jovywood`

And the virtual env at:
`/home/myburgh/venv/jovy_venv`

All on bbking. 

Can meet based on if/what you're able to get something working with it?
Thanks.

**Comment by landmanbester** [comment]
Ah, I see it is looking in `/home/myburgh/venv/jovy_venv/lib/python3.10/site-packages/jove/parser/gpr_smooth.yaml` for `gpr_smooth.yaml`. I didn't have that in the `MANIFEST.in` file so that wouldn't have worked. Did you install with `-e` though because it should not be looking in site-packages if you did?

**Comment by talonmyburgh** [comment]
I was not installing in developer mode - done so now and it appears to work.
